### ISSUE TITLE
Proposal: Store cpacs_gen revision to generated code

### ISSUE THREAD

**Issue by rainman110** [RlanderRISCSW/cpacs_tigl_gen#10]
Currently, there is no way to determine, with which version of cpacs_gen the tigl code was created.

I assume, that at some point this could be an issue.

Therefore, we should store the git rev / tag next to the generated code. There are probably many ways to do it, here are some ideas:
 - Reference the cpacs_gen in tigl directly as a git submodule. No change has to be made to cpacs_gen
 - Store the revision number into a file inside the src/generated directory. This file will be always updated, when the cpacs_gen revision changes. This can be done like in TiGL for nightly builds: https://github.com/DLR-SC/tigl/blob/master/CMakeLists.txt#L49

@dixxi What do you think is the best way to achieve this?

**Comment by dixxi** [comment]
Just as we have discussed today, I'll try the submodule.
