### ISSUE TITLE
Empty lines should not contain white spaces

### ISSUE THREAD

**Issue by rainman110** [RlanderRISCSW/cpacs_tigl_gen#15]
This is more like a wish than an issue. It would be good, if empty lines in the generated code do not contain white spaces for indentation.

This is in particular useful, if the code is transformed via clang-format etc., which just removes the whitespaces.

**Comment by bernhardmgruber** [comment]
I wanted to do this anyway at some point. It's also not hard to implement.

**Comment by rainman110** [comment]
Great! I tried it yesterday... but didn't manage to do it ;)
